# -*- coding: utf-8 -*-
"""Entrega_02

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q2maa4YnOA6fiapx8IAOEouWvNFVaBBj
"""

from prettytable import PrettyTable

# Crear una tabla
tabla = PrettyTable()
tabla.field_names = ["País", "Porcentaje"]

# Datos desordenados
datos = [
    ["Finlandia", 64.3],
    ["España", 63.6],
    ["Chile", 58.3],
    ["Bélgica", 57.1],
    ["Suecia", 47.8],
    ["Canadá", 48.6],
    ["Países Bajos", 50.0],
    ["Alemania", 50.0],
    ["Noruega", 50.0],
    ["Colombia", 50.0],
    ["Estonia", 42.9],
    ["Lituania", 42.9],
    ["Letonia", 42.9],
    ["Suiza", 42.9],
    ["México", 42.1],
    ["Costa Rica", 45.5],
    ["Australia", 43.5],
    ["Luxemburgo", 37.5],
    ["Eslovenia", 38.5],
    ["Francia", 35.3],
    ["Portugal", 41.2],
    ["Islandia", 41.7],
    ["Italia", 26.7],
    ["Dinamarca", 31.8],
    ["Irlanda", 23.1],
    ["Reino Unido", 33.3],
    ["Estados Unidos", 33.3],
    ["Grecia", 10.5],
    ["Hungría", 9.1],
    ["Israel", 12.5],
    ["Japón", 8.3],
    ["Corea del Sur", 16.7],
    ["Bulgaria", 15.8],
    ["México", 42.1],
    ["Estonia", 42.9],
    ["Rumania", 10.0],
    ["República Checa", 7.1],
    ["Eslovaquia", 14.3],
    ["Polonia", 17.6],
    ["Turquía", 5.9],
    ["OECD - Average", 35.7]
]

# Ordenar los datos de mayor a menor según el porcentaje
datos_ordenados = sorted(datos, key=lambda x: x[1], reverse=True)

# Agregar los datos ordenados a la tabla
for dato in datos_ordenados:
    tabla.add_row(dato)

# Imprimir la tabla ordenada
print(tabla)